version: "0.0.1"
environment: dev

elastic:
  username: user
  password: password
  url: http://localhost:9200
  indices:
    map:
      read: "terranova-map-*"
      write: "terranova-map"
    template:
      read: "terranova-template-*"
      write: "terranova-template"
    dataset:
      read: "terranova-dataset-*"
      write: "terranova-dataset"
    userdata:
      read: "terranova-userdata-*"
      write: "terranova-userdata"

datasources:
  esdb:
    cache_file: "esdb_cache_sample.sqlite"
    api_key: "abcdefg"
    url: "https://esdb"
  google_sheets:
    credential_type: static
    cache_file: /var/tmp/google_sheets.sqlite
    static:
      token_files:
        - ./example_jwt.json
  service_datasource:
    cache_file: /var/tmp/services.sqlite
    api_key: SAMEAPIKEYASABOVE
    url: https://esdb.es.net/esdb_api/v1/
    table_name: service

keycloak:
  server: "keycloak-east.es.net"
  realm: "esnet_realm"
  client: "foo"

auth:
  backend: keycloak
  read_scope: "terranova:maps:read"
  write_scope: "terranova:maps:write"
  publish_scope: "terranova:maps:publish"
  admin_scope: "terranova:admin"

# Optional - configure trace / log OTLP exporting
#otlp:
#  endpoint: https://localhost:8200/intake/v2/events
#  secret_key: abcdefg